package com.almustkbal.pacs.domain;

public enum PrivilegeName {

	DICOM_VIEWER, DASHBOARD_VIEW, USERS_VIEW, USERS_EDIT, APPICATION_ENTITY_EDIT, DIRECTORY_WATCHER_EDIT,
	DICOMS_UPLOADER, DICOMS_SEARCH, DIRECTORY_WATCHER_VIEW, APPICATION_ENTITY_VIEW
}
